### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NoSignalBeep** [NoComment1105/DeepslateCutting#14]
### DeepslateCutting and Minecraft Version

deepslatecutting-fabric1.7.0

### Operating System

Windows 11

### Java Version

Java 17.07

### Reproduction Steps

1. Game loads
2. I go to use stonecutter
3. Game crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-07-31 11:50:49
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "tx" because "this.space" is null
	at dev.emi.emi.screen.EmiScreenManager$SidebarPanel.updateWidgetPosition(EmiScreenManager.java:1386)
	at dev.emi.emi.screen.EmiScreenManager.updateSidebarButtons(EmiScreenManager.java:800)
	at dev.emi.emi.screen.EmiScreenManager.addWidgets(EmiScreenManager.java:795)
	at net.minecraft.class_437.handler$ckc000$emi$init(class_437.java:1662)
	at net.minecraft.class_437.method_25423(class_437.java:305)
	at com.plusls.MasaGadget.tweakeroo.handRestockCrafting.RestockUtil.tryCraftingRestocking(RestockUtil.java:47)
	at fi.dy.masa.tweakeroo.util.InventoryUtils.handler$ena000$masa_gadget_mod-1_20_1$PreRestockOnFailed(InventoryUtils.java:1239)
	at fi.dy.masa.tweakeroo.util.InventoryUtils.preRestockHand(InventoryUtils.java:348)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.processRightClickBlockWrapper(PlacementTweaks.java:718)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.tryPlaceBlock(PlacementTweaks.java:602)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.onProcessRightClickBlock(PlacementTweaks.java:365)
	at net.minecraft.class_310.redirect$gmk000$tweakeroo$onProcessRightClickBlock(class_310.java:3091)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.emi.emi.screen.EmiScreenManager$SidebarPanel.updateWidgetPosition(EmiScreenManager.java:1386)
	at dev.emi.emi.screen.EmiScreenManager.updateSidebarButtons(EmiScreenManager.java:800)
	at dev.emi.emi.screen.EmiScreenManager.addWidgets(EmiScreenManager.java:795)
	at net.minecraft.class_437.handler$ckc000$emi$init(class_437.java:1662)
	at net.minecraft.class_437.method_25423(class_437.java:305)
	at com.plusls.MasaGadget.tweakeroo.handRestockCrafting.RestockUtil.tryCraftingRestocking(RestockUtil.java:47)
	at fi.dy.masa.tweakeroo.util.InventoryUtils.handler$ena000$masa_gadget_mod-1_20_1$PreRestockOnFailed(InventoryUtils.java:1239)
	at fi.dy.masa.tweakeroo.util.InventoryUtils.preRestockHand(InventoryUtils.java:348)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.processRightClickBlockWrapper(PlacementTweaks.java:718)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.tryPlaceBlock(PlacementTweaks.java:602)
	at fi.dy.masa.tweakeroo.tweaks.PlacementTweaks.onProcessRightClickBlock(PlacementTweaks.java:365)
	at net.minecraft.class_310.redirect$gmk000$tweakeroo$onProcessRightClickBlock(class_310.java:3091)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['No_Signal_Beep'/81, l='ClientLevel', x=261.37, y=37.00, z=1308.37]]
	Chunk stats: 262144, 2362
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,69,784), Section: (at 0,5,0 in 7,4,49; chunk contains blocks 112,-64,784 to 127,319,799), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Level time: 41252254 game time, 46101235 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Lower Terrain.zip, file/Faithful 64x - Beta 9 podzol sides, file/QuieterShit.zip, file/LowerFire+[1.18.x].zip, file/Rainbow XP Bar 32x.zip, file/grey_concrete_background.zip, file/Square-Barrels-F32x-main, file/clearvisionglass-32x-1-19-3-e120.zip, file/Redstone+Utilities-v2.1+[1.19.x].zip, file/Clearer-Connected-Tinted-Glass-64x.zip, file/Glowing Ores, file/Clean Bedrock.zip, file/3d-rails-e1701.zip, file/32x Splash Experience Bottle 1.14-1.19.zip, file/Faithful-Java-32x-Visual_Banner_Patterns_v1.0.zip, file/Fences Overhaul.zip, file/NoPumpkinBlur-rv1.3.zip, file/goat-horns-plus-32x.zip, file/strengthen ladder-dark_oak, file/Dark Powdered Inventory v2 (1).zip, file/Bushy Leaves for Faithful 32x V1.3.zip, file/Signs Overhaul.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1316172416 bytes (1255 MiB) / 3837788160 bytes (3660 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2684
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.20
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.20
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 37372.98
	Virtual memory used (MB): 17453.14
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.10
		betterstats: Better Statistics Screen 2.10.3+1.20.1
			tcdcommons: TCD Commons API 2.10.2+1.20.1
		betterthanmending: BetterThanMending 1.3.0
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4-SNAPSHOT-build.21
		blasting_plus_mr: Blasting Plus 1.1
		bobby: Bobby 5.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a82
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b82
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 20.0.2
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		carpet: Carpet Mod 1.4.112+v230608
		carpet-addons-not-found: Carpet Addons Not Found 1.2.2
		carpet-autocraftingtable: Carpet-AutoCraftingTable 1.4.57
		carpet-extra: Carpet Extra 1.4.115
		carpet-fixes: Carpet Fixes 1.20-1.16.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		carpet-tctc-addition: Carpet TCTC Addition 2.2.201+8009659-stable
			carpet-tctc-addition-1_20_1: Carpet TCTC Addition for 1.20.1 2.2.201+8009659-stable
		charmofundying: Charm of Undying 6.4.2+1.20.1
			spectrelib: SpectreLib 0.13.13+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.65
		connectiblechains: Connectible Chains 2.2.1+1.20.1
		continuity: Continuity 3.0.0-beta.2+1.20
		craftify: Craftify 1.11.0
			elementa: Elementa 590
			universalcraft: UniversalCraft 277
			vigilance: Vigilance 284
		deepslatecutting: Deepslate Cutting 1.7.0
		deepslatetweaks: Deepslate Tweaks 1.2
		easyanvils: Easy Anvils 8.0.0
		easymagic: Easy Magic 8.0.0
		easyshulkerboxes: Easy Shulker Boxes 8.0.0
			puzzlesapi: Puzzles Api 8.0.2
				puzzlesaccessapi: Puzzles Access Api 8.0.5
		emi: EMI 1.0.11+1.20.1+fabric
		emi_loot: EMI Loot 0.6.4.1+1.20.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		explorerscompass: Explorer's Compass 1.20.1-2.2.2-fabric
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fallingleaves: Falling Leaves 1.15.2+1.20.1
		fancymenu: FancyMenu 2.14.7
		flowermap: Flower Map 1.3.0
		followersteleporttoo: Followers Teleport Too 2.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		gammautils: Gamma Utils 1.7.15
		improvedvanilla: ImprovedVanilla 1.20.1-1.6.4
		indium: Indium 1.0.21+mc1.20.1
		inventorio: Inventorio 1.9.2
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller 0.20.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.22
		konkrete: Konkrete 1.6.1
		libipn: libIPN 3.0.2
		librarian-trade-finder: Librarian Trade Finder 2.0.1
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		magiclib: MagicLib 0.7.346+e235d92-stable
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.346+e235d92-stable
		malilib: MaLiLib 0.16.1
		masa_gadget_mod: Masa Gadget 3.2.311+aae0554-stable
			masa_gadget_mod-1_20_1: Masa Gadget for 1.20.1 3.2.311+aae0554-stable
		masaadditions: MasaAdditions 1.2.0
		mindfuldarkness: Mindful Darkness 8.0.0
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		minitweaks: MiniTweaks 1.4.0
		modmenu: Mod Menu 7.1.0
		moonphaseinfoplus: Moon Phase Info+ 1.1
		moreculling: More Culling 1.20-0.18.1
			conditional-mixin: conditional mixin 0.3.2
		naturescompass: Nature's Compass 1.20.1-2.2.1-fabric
		notes: Notes 1.20.1-2.1.0-fabric
		placeableblazerods: Placeable Blaze Rods 3.1
		polymorph: Polymorph 0.49.0+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
		portallinkingcompass: Portal Linking Compass 1.0.0-beta.1+mc1.20
		puzzleslib: Puzzles Lib 8.0.7
		reeses-sodium-options: Reese's Sodium Options 1.5.1+mc1.20-build.74
		rug: Rug 1.20.1-1.4.2
			sgui: sgui 1.2.2+1.20
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.0
		sherdduplication: SherdDuplication 2.0.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		spyglass-improvements: Spyglass Improvements 1.4+mc1.20+fabric
		tall-flower-pots: Tall Flower Pots 0.1.2
		tipsmod: Tips 12.0.1
		treeharvester: Tree Harvester 8.2
		trinkets: Trinkets 3.7.0
		tweakermore: TweakerMore 3.13.1
		tweakeroo: Tweakeroo 0.17.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 23.6.0
		xaeroworldmap: Xaero's World Map 1.31.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.3+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
	Loaded Shaderpack: ComplementaryReimagined_r2.2.1.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4090/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Lower Terrain.zip, file/Faithful 64x - Beta 9 podzol sides, file/QuieterShit.zip (incompatible), file/LowerFire+[1.18.x].zip (incompatible), file/Rainbow XP Bar 32x.zip (incompatible), file/grey_concrete_background.zip, file/Square-Barrels-F32x-main (incompatible), file/clearvisionglass-32x-1-19-3-e120.zip (incompatible), file/Redstone+Utilities-v2.1+[1.19.x].zip (incompatible), file/Clearer-Connected-Tinted-Glass-64x.zip (incompatible), file/Glowing Ores (incompatible), file/Clean Bedrock.zip (incompatible), file/3d-rails-e1701.zip, file/32x Splash Experience Bottle 1.14-1.19.zip (incompatible), file/Faithful-Java-32x-Visual_Banner_Patterns_v1.0.zip (incompatible), file/Fences Overhaul.zip, file/NoPumpkinBlur-rv1.3.zip (incompatible), file/goat-horns-plus-32x.zip (incompatible), file/strengthen ladder-dark_oak, file/Dark Powdered Inventory v2 (1).zip (incompatible), file/Bushy Leaves for Faithful 32x V1.3.zip, file/Signs Overhaul.zip
	Current Language: en_us
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900K
	Server Running: true
	Player Count: 1 / 8; [class_3222['No_Signal_Beep'/81, l='ServerLevel[The Chaos Rift]', x=261.37, y=37.00, z=1308.37]]
	Data Packs: vanilla, fabric, file/6 Trapdoors - 1.2.2.zip, file/Beehive_Lore_1.5.2.zip, file/Blasting Plus 1.1.zip (incompatible), file/Copper_Beacons_1.1.2.zip, file/Craftable Notch Apples (MC 1.20.x).zip, file/Disenchanting_1.4.2.zip, file/Dropper_to_Dispenser_MC1.20.x.zip, file/End_Ship_Beacons_1.4.2.zip, file/Faithful+Addon+-+Blue+Ancient+Debris+64x.zip (incompatible), file/Item_Magnet_2.6.zip, file/MobMuffler_1.5.2.zip, file/Sandstone_Dyeing.zip, file/Shulker_Respawning_1.5.1.zip, file/Silk_Touch_Amethyst_1.1.2.zip, file/Straight_to_Shapeless_MC1.20.x.zip, file/Trader_Notify_1.4.2.zip, file/Universal_Dyeing_MC1.20.x.zip, file/Unpackables_MC1.20.x.zip, file/VanillaTweaks_c229238_MC1.20.x.zip, file/VanillaTweaks_c432881_MC1.20.x.zip, file/Woodcutter-5.0 (1).zip, file/anti enderman grief v1.1.4 (MC 1.20.x).zip, file/anti ghast grief v1.1.4 (MC 1.20.x).zip, file/armored elytra v1.0.7 (MC 1.20.x).zip, file/bat membranes v1.0.5 (MC 1.20.x).zip, file/cauldron concrete v2.0.7 (MC 1.20.x).zip, file/custom nether portals v2.3.7 (MC 1.20.x).zip, file/double shulker shells v1.3.4 (MC 1.20.x).zip, file/dragon drops v1.3.4 (MC 1.20.x).zip, file/fast leaf decay v2.0.7 (MC 1.20.x).zip, file/homes v1.5.5 (MC 1.20.x).zip, file/kill empty boats v1.1.5 (MC 1.20.x).zip, file/multiplayer sleep v2.6.4 (MC 1.20.x).zip, file/nether portal coords v1.1.4 (MC 1.20.x).zip, file/terracotta rotation wrench v1.1.5 (MC 1.20.x).zip, file/VanillaTweaks_c856620_MC1.20.x.zip, file/RugData (incompatible), file/Craftable Chainmail Armor 1.20.zip, file/unpackableblocksv2.zip, file/BlazeandCaves Advancements Pack 1.16.2.zip, file/More_Bricks_MC1.20.x.zip, file/villager death messages v1.2.5 (MC 1.20.x).zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

### Additional context

I have replicated this multiple times and when I remove the mod, I have no issues,

**Comment by NoSignalBeep** [comment]
I'm going to close this for now, I know it did cause issues with my game running, but I'm having issues without it now, so I'm doing some further troubleshooting.
